# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jon Vaysman
title: Computer Science
email: jonvaysman@gmail.com
website: Javeh.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  Javeh
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: JonVaysman
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
url: https://www.github.com/Javeh
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jon and I'm a student currently studying Computer Science at The University Of Michigan. As a hobbyist, I've goten a lot of experience with <mark>Java</mark> and <mark>Unix</mark> server management. I'm currently looking for a software engineering internship to flesh out my skills working on a team.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Nevermore
        link: https://plorthos.itch.io/nevermore
        icon: fab fa-itch-io
        link: github.com/Javeh/Nevermore
        icon: fab fa-github
        quote: >
          Fireball!
        description: |
          This was my capstone project. The goal of the class was to spend the semester conceiving, pitching, and developing a product. We chose to create a video game where players could come up with their own magical spells that would be intepreted by the game's AI.
          I worked on a team of 8 people, half developing the AI side of things, and half developing the game side, which was my subteam. We developed the game in <Mark>C# (C Sharp)</mark> using the <mark>Unity</mark> game engine. I mainly worked on UI elements, but also worked on implementing multiplayer gameplay features using Unity's networking API.
          I also helped implement a server using <mark>Flask</mark> in the <mark>Python</mark> language, that utilized <mark>MongoDB</mark>, a <mark>NoSQL</mark> database, to store previously computed spells, reducing latency and cost incurred by querying GPT-3 for those spells
      - layout: top-middle
        title: JFactions
        link: github.com/Javeh/JFactions
        # link_text: Project Website
        additional_links:
          - title:  Javeh/JFactions 
            icon: fab fa-github
            url: github.com/Javeh/JFactions
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably my largest independent project.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>MySQL</mark>. It is a server-side plugin for the Java edition of Minecraft. It allows users to claim territory for different factions, based on their activity in the game. The more a user plays, the more points they earn, which means they can claim more land. I used MySQL to track land claims, restrictions players set on land they controlled, and player statistics.
      - layout: top-middle
        title: Draco
        link: https://github.com/Javeh/Draco
        additional_links:
          - title: Javeh/Draco
            icon: fab fa-github
            url: github.com/Javeh/Draco
        description: |

          When I was the programming lead for my FIRST robotics team in high school, I managed and created a majority of the code for our robot. The robot this code was written for went on to win an FRC Control Systems Award.
          I feel it is releveant to include because it demonsrates the use of multiple <mark>APIs</mark> and the <mark>Java</mark> programming language.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Internal Drive (iD) Tech Camps
        link: idtech.com
        link_text: iDTech.com
        sub_title: Instructor
        caption: Summer 2021
        #quote: >
          #Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            As an instructor, I primarily taught students over Zoom due to the COVID-19 Pandemic. My course topics included Python, Javascript, and Java. Additionally, I worked as a support team member, troubleshooting IDE and dependency problems for customers in one-on-one zoom calls.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Michigan
        caption: 2019 - Present
        sub_title: BSc Computer Science
        quote: >
          Established in 1817, The University of Michigan is the #3 public university in the United States according to U.S. News and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at UM I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I was and am actively involved in a number of clubs here, including:

          The University of Michigan Dearborn Campus Student Government as Treasurer

          The University of Michigan - Dearborn Campus Political Science Association as a Recruitment Committee member.

          The Michigan Student Voter Council, an initiative to increase voter participation among college students throughout the state, in collaboration with the Secretary of State's office.

          Michigan Quiz Bowl

          Michigan Table Tennis

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Table Tennis
      - Trivia/Quiz Bowl
      - Kayaking

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
